### ISSUE TITLE
update planned ?

### ISSUE THREAD

**Issue by katian** [Arnatious/qbittorrent-snap#14]
qBittorrent is currently @ version 4.4.0

https://github.com/qbittorrent/qBittorrent/tags

Thanks

**Comment by Arnatious** [comment]
Yep! Unfortunately upstream doesn't have a "latest" tag so I have to manually update this repo when there's a new minor version series.

**Comment by katian** [comment]
Thanks for your reply @Arnatious

**Comment by Arnatious** [comment]
https://github.com/Arnatious/qbittorrent-snap/issues/15 tracking the bug blocking me from updating
