### ISSUE TITLE
Icon Missing in Notification

### ISSUE THREAD

**Issue by wsamh** [Arnatious/qbittorrent-snap#2]
the icon is missing in the notification bar on Kde. I'm on kubuntu 20.04.

![Screenshot_20200707_125014-2](https://user-images.githubusercontent.com/67978594/86835398-e4fe2900-c050-11ea-961d-3fe1798783f5.png)

**Comment by Arnatious** [comment]
The icon appears to be fixed in the candidate version as of today. Possibly an upstream fix, I'd tinkered with it for ages trying the kde platform snaps, kde-neon extension, etc to no avail.

**Comment by Arnatious** [comment]
I'm leaving this issue open until I verify it works on the plasma/kubuntu desktop

**Comment by neswii** [comment]
Getting the blank icon on Debian Bullseye with KDE stable. From my research the bug may be related to SNI implementation, but I am very inexperienced. Maybe you will find a fix in the best thread I found about the problem: https://github.com/qbittorrent/qBittorrent/issues/9518

**Comment by Arnatious** [comment]
As an update to anyone following this there was a huge discussion [here](https://forum.snapcraft.io/t/how-do-i-make-my-tray-icon-display-in-ubuntu-budgie-in-my-pyqt5-app/26515) on the snapcraft forums to figure out why.

**Comment by Arnatious** [comment]
Looks like ilya-feldin at snapcraft.io figured it out
https://forum.snapcraft.io/t/how-do-i-make-my-tray-icon-display-in-ubuntu-budgie-in-my-pyqt5-app/26515/26
I'll try to see about upstreaming a fix
