### ISSUE TITLE
Any chance to get 4.3.1 ?

### ISSUE THREAD

**Issue by CryptoEU** [Arnatious/qbittorrent-snap#4]
Hi Ted,
will you update to the qBittorrent 4.3.1?

**Comment by Arnatious** [comment]
@CryptoEU @mouaadsk very late to the party but 4.3.x is now available on channel `latest/candidate`

**Comment by Arnatious** [comment]
> 
> 
> @Arnatious
> 
> thanks Ted.
> 
> Could you be so kind and tell me, how I can "update" to the candidate version, please?
> 
> sudo snap install qbittorrent-arnatious
> sudo snap install qbittorrent-arnatious --candidate
> 
> brings just a "...already installed"
> 
> Because of torrents etc. I would try to avoid a new clean install after a complete uninstall of the old version.

Sure - you need to use `snap refresh` when its already installed.

`sudo snap refresh qbittorrent-arnatious --channel=candidate`

**Comment by Arnatious** [comment]
In addition, when uninstalling snaps, configuration and state files and the like are left behind unless the `--purge` option is used with remove. You in theory shouldn't lose anything uninstalling and reinstalling a snap.

**Comment by CryptoEU** [comment]
@Arnatious 
I am sorry Ted, but it looks like, I am too stupid for that :D Sorry.

sudo snap refresh qbittorrent-arnatious --channel=candidate
....
snap list
Name                   Version                     Rev    Tracking          Publisher   Notes

qbittorrent-arnatious  0.2                         73     latest/candidate  arnatious   -

restarting qbittorrent -> still 4.2.5
restart the PI, no effect.

Tried to use edge -> 
qbittorrent-arnatious  0.2                         73     latest/edge    arnatious   -

**Comment by Arnatious** [comment]
No worries! It takes a bit of time for updates to propagate, it may not have reached you yet. Try again now and let me know what happens?

**Comment by CryptoEU** [comment]
:D ok, really stupid me.

I run the Raspbian Buster 10, thats armhf.
If I check 
https://snapcraft.io/qbittorrent-arnatious
at the armhf is still the 0.2 available

**Comment by Arnatious** [comment]
Ahh yeah unfortunately core20 only supports 64 bit OS's, I'll need to make a separate branch to build/upload the 32bit systems in a CI pipeline
