### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by tehmasterer** [Arnatious/qbittorrent-snap#9]
qBittorrent is currently @ version 4.3.9. The snap is 11 months behind.

Thanks

**Comment by Arnatious** [comment]
Updated candidate/latest to 4.3.9 - I'll push to stable once I get confirmation it works

**Comment by CryptoEU** [comment]
It would be great, if you would finally update armf too.... :(

**Comment by tehmasterer** [comment]
Thanks for the update!

**Comment by Arnatious** [comment]
> It would be great, if you would finally update armf too.... :(

@CryptoEU Its a bit difficult since I don't have an armhf board laying around to test on. I'll try but the latency of testing via remote-build is a pain
